# ActionGlass Configuration
# Realistic glass breaking mechanics for Minecraft servers

# Feature toggles - Enable or disable specific glass breaking mechanics
features:
  # Allow arrows and other projectiles to break glass
  arrow-breaking: true
  
  # Allow players with elytra to break glass while gliding at high speed
  elytra-breaking: true
  
  # Allow players to break glass when falling at high speed
  falling-breaking: true
  
  # Allow players to break glass when running/sprinting through it
  running-breaking: true
  
  # Enable automatic glass regeneration after breaking
  regeneration: true

# General settings
settings:
  # Minimum speed required to break glass (blocks per tick)
  # Higher values = need more speed to break glass
  # Lower values = easier to break glass
  minimum-speed: 0.3
  
  # Cooldown between glass breaking events per player (milliseconds)
  # Prevents spam breaking and improves performance
  glass-break-cooldown: 500
  
  # Delay before broken glass regenerates (milliseconds)
  # 20 ticks = 1 second, so 6000 = 5 minutes
  regeneration-delay: 6000

# Break radius settings - How many blocks around the impact point get broken
# Larger radius = more dramatic breaking effect
# Smaller radius = more precise breaking
break-radius:
  # Projectile break radiuses
  arrow: 1          # Arrows break small holes
  trident: 2        # Tridents break medium holes  
  wind-charge: 3    # Wind charges break large holes
  
  # Movement break radiuses
  elytra: 2         # Elytra creates medium break patterns
  falling: 2        # Falling creates medium break patterns
  running: 1        # Running creates small break patterns
  sprinting: 2      # Sprinting creates larger break patterns

# Advanced settings for fine-tuning
advanced:
  # Enable debug messages in console (useful for troubleshooting)
  debug-mode: false
  
  # Maximum number of glass blocks that can be broken simultaneously
  # Helps prevent server lag from massive glass structures
  max-simultaneous-breaks: 50
  
  # Enable particle effects when glass breaks
  break-particles: true
  
  # Enable sound effects when glass breaks
  break-sounds: true
  
  # Enable particle effects when glass regenerates
  regeneration-particles: true
  
  # Enable sound effects when glass regenerates
  regeneration-sounds: true
  
  # Minimum distance between break events to prevent chain reactions
  min-break-distance: 1.0

# World-specific settings
# You can disable the plugin in specific worlds
worlds:
  # Enable ActionGlass in these worlds (empty list = all worlds)
  enabled-worlds: []
  
  # Disable ActionGlass in these worlds
  disabled-worlds:
    - "creative_world"
    - "build_world"

# Glass type specific settings
# Configure different behaviors for different types of glass
glass-types:
  # Regular glass blocks
  glass:
    enabled: true
    break-resistance: 1.0    # Multiplier for break difficulty
    regeneration-time: 1.0   # Multiplier for regeneration delay
  
  # Stained glass blocks
  stained-glass:
    enabled: true
    break-resistance: 1.0
    regeneration-time: 1.0
  
  # Glass panes (thinner, easier to break)
  glass-panes:
    enabled: true
    break-resistance: 0.7    # Easier to break than blocks
    regeneration-time: 0.8   # Faster regeneration

# Player group specific settings
# Different settings for different permission groups
player-groups:
  # Default settings for all players
  default:
    break-multiplier: 1.0    # Speed multiplier for breaking glass
    cooldown-multiplier: 1.0 # Cooldown multiplier
  
  # Settings for VIP players (requires permission: actionglass.vip)
  vip:
    break-multiplier: 1.2    # 20% easier to break glass
    cooldown-multiplier: 0.8 # 20% shorter cooldown
  
  # Settings for admin players (requires permission: actionglass.admin)
  admin:
    break-multiplier: 2.0    # Much easier to break glass
    cooldown-multiplier: 0.5 # Much shorter cooldown

# Integration settings for other plugins
integrations:
  # WorldGuard integration
  worldguard:
    enabled: true
    respect-regions: true    # Don't break glass in protected regions
    
  # GriefPrevention integration  
  griefprevention:
    enabled: true
    respect-claims: true     # Don't break glass in claimed areas
    
  # Towny integration
  towny:
    enabled: true
    respect-towns: true      # Don't break glass in towns
    
  # Factions integration
  factions:
    enabled: true
    respect-territory: true  # Don't break glass in faction territory

# Performance settings
performance:
  # Enable async processing for better performance
  async-processing: true
  
  # Maximum glass blocks to process per tick
  max-blocks-per-tick: 10
  
  # Enable caching for better performance
  enable-caching: true
  
  # Cache cleanup interval (ticks)
  cache-cleanup-interval: 1200

# Experimental features (may be unstable)
experimental:
  # Enable realistic glass crack patterns before breaking
  crack-patterns: false
  
  # Enable glass shard drops when breaking
  glass-shards: false
  
  # Enable chain breaking for connected glass structures
  chain-breaking: false
  
  # Enable different break patterns based on impact angle
  angle-based-breaking: false

# Configuration version (do not modify)
config-version: 1
