# ActionGlass Configuration File
config-version: 1

# Glass Breaking Settings
glass-breaking:
  enabled: true
  minimum-speed: 0.3
  restore-time: 30
  
  # Elytra Breaking
  elytra-breaking: true
  elytra-min-speed: 0.6
  elytra-break-radius: 3.5
  
  # Sprint Breaking
  sprint-breaking: true
  sprint-min-speed: 0.4
  sprint-break-radius: 2.5
  
  # Fall Breaking
  fall-breaking: true
  fall-break-height: 4.0
  fall-min-speed: 0.5
  fall-break-radius: 3.0

# Effects
effects:
  sounds:
    glass-break:
      enabled: true
      volume: 1.0
      pitch: 1.0
    glass-restore:
      enabled: true
      volume: 0.5
      pitch: 1.2
  particles:
    glass-break:
      enabled: true
      count: 30
    glass-restore:
      enabled: true
      count: 15

# Statistics
statistics:
  enabled: true

# Integrations
integrations:
  worldguard:
    enabled: true
  towny:
    enabled: true

# Debug mode
debug: true

# Performance settings
performance:
  max-chain-break-size: 50  # Maximum number of connected glass blocks to break in one chain
  enable-async-processing: true  # Process large operations asynchronously
