name: ActionGlass
version: 1.0.0
main: com.actionglass.ActionGlass
api-version: 1.19
author: FizzleTits
description: Realistic glass breaking plugin

commands:
  actionglass:
    description: ActionGlass main command
    usage: /actionglass [toggle|debug|test|reload]
    permission: actionglass.admin
    aliases: [ag, aglass]

permissions:
  actionglass.admin:
    description: Allows use of ActionGlass admin commands
    default: op
  actionglass.break:
    description: Allows breaking glass through movement/projectiles
    default: true
